export default function getItems() {
  return [
    {
      id: 1,
      itemName: "Allen Solly Shirt",
      category: "Fashion",
      price: "1,399",
      isCarted: false,
    },
    {
      id: 2,
      itemName: "Iphone 13",
      category: "Electronics",
      price: "71,999",
      isCarted: false,
    },
    {
      id: 3,
      itemName: "Apple Watch SE 2",
      category: "Fashion",
      price: "37,999",
      isCarted: false,
    },
    {
      id: 4,
      itemName: "Nike Shoe",
      category: "Fashion",
      price: "4,599",
      isCarted: false,
    },
    {
      id: 5,
      itemName: "LG LED Smart TV",
      category: "Appliances",
      price: "48,999",
      isCarted: false,
    },
    {
      id: 6,
      itemName: "Macbook Pro M2",
      category: "Electronics",
      price: "1,21,990",
      isCarted: false,
    },
    {
      id: 7,
      itemName: "Samsung Fridge",
      category: "Appliances",
      price: "24,990",
      isCarted: false,
    },
    {
      id: 8,
      itemName: "Office Chair",
      category: "Furniture",
      price: "9,960",
      isCarted: false,
    },
    {
      id: 9,
      itemName: "Adidas T-Shirt",
      category: "Fashion",
      price: "899",
      isCarted: false,
    },
    {
      id: 10,
      itemName: "Sony Headphone",
      category: "Electronics",
      price: "17,999",
      isCarted: false,
    },
    {
      id: 11,
      itemName: "Apple Airpods Pro",
      category: "Electronics",
      price: "22,500",
      isCarted: false,
    },
    {
      id: 12,
      itemName: "Samsung A/C",
      category: "Appliances",
      price: "31,999",
      isCarted: false,
    },
    {
      id: 13,
      itemName: "Samsung Washing Machine",
      category: "Appliances",
      price: "22,490",
      isCarted: false,
    },
    {
      id: 14,
      itemName: "Sofa",
      category: "Furniture",
      price: "13,000",
      isCarted: false,
    },
    {
      id: 15,
      itemName: "Office Table",
      category: "Furniture",
      price: "5,170",
      isCarted: false,
    },
    {
      id: 16,
      itemName: "Bed",
      category: "Furniture",
      price: "7,999",
      isCarted: false,
    },
  ];
}
